In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

#### 1. Numpy를 활용한 데이터셋 생성

In [2]:
# 도미 + 빙어 데이터 
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8, 
                10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7, 
                7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [3]:
# test
np.column_stack(([1, 2, 3],[4, 5, 6]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# fish_data = [[l,w] for l, w in zip(fish_length, fish_weight)]
fish_data = np.column_stack((fish_length,fish_weight))

In [5]:
print(fish_data[:5])# 처음(0)부터 ~ 4번까지 

[[ 25.4 242. ]
 [ 26.3 290. ]
 [ 26.5 340. ]
 [ 29.  363. ]
 [ 29.  430. ]]


In [6]:
# test
print(np.ones(35))
print(np.zeros(14))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# concatenate() 2개의 배열을 합쳐서 한줄로!
fish_target = np.concatenate((np.ones(35), np.zeros(14)))

In [8]:
fish_target

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. Sckit_learn으로 Train/Test 나누기

In [9]:
#Default: 75%:25%
train_input, test_input, train_target, test_target = train_test_split(fish_data, fish_target, random_state = 42)

In [10]:
print(train_input.shape, test_input.shape)

(36, 2) (13, 2)


In [11]:
print(train_target.shape, test_target.shape)

(36,) (13,)


In [12]:
print(test_target)

[1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
# 도미 35마리, 빙어 14마리 2.5:1 비율
# 생선

In [16]:
# stratify=fish_target Class 비율에 맞게 데이터셋 분할
train_input, test_input, train_target, test_target = train_test_split(fish_data, fish_target, stratify=fish_target, random_state = 42)

In [ ]:
print(test_target)

#### 3. 수상한 도미 한 마리

In [ ]:
kn = KNeighborsClassifier
kn.fit(train_input, train_target)
kn.score(test_input, test_target)

In [ ]:
# 도미: 1, 빙어: 0
print(kn.predict([25, 150])) #빙어로 분류

In [ ]:
plt.scatter(train_input[:0], train_input[:1])
plt.scatter(25, 150, marker="^")
plt.scatter(train_input[indexed, 0]), train_input[indexed,1], marker = '0')
plt.xlabel('length')
plt.ylabel('weight')
plt.show

In [ ]:
print(train_input[indexes])

In [ ]:
print(train_target[indexes])

In [ ]:
print(distances)

#### 4. 정규화
Normalization

In [ ]:
plt.scatter(train_input[:0], train_input[:1])
plt.scatter(25, 150, marker="^")
plt.scatter(train_input[indexed, 0]), train_input[indexed,1], marker = '0')
plt.xlim(0,1000)
plt.xlabel('length')
plt.ylabel('weight')
plt.show

#### 표준점수(standard score) 또는 z score를 사용한 정규화
- 분산: 데이터에서 평균의 뺀 값을 모두 제곱한 다음 평균 냄
- 표준편차: 분산의 제곱근, 데이터가 분산된 정도
- 표준점수: 각 데이터가 원점에서 몇 표준편차만큼 떨어져 있는지를 나타냄

> 표준점수 공식: (특징 =- mean)/std

In [ ]:
mean = np.mean(train_input, axis=0)
std = np.std(train_input, axis=0)

print(mean, std)

In [ ]:
# 브로드캐스팅
train_scaled = (train_input - mean) / std

In [ ]:
train_scaled

In [ ]:
plt.scatter(train_scaled[:0], train_scaled[:1])
plt.scatter(25, 150, marker="^")
plt.xlabel('length')
plt.ylabel('weight')
plt.show
# ctrl X 한 줄 삭제

In [ ]:
new = ([25, 150]- mean) / std

In [ ]:
plt.scatter(train_scaled[:0], train_scaled[:1])
plt.scatter(new[0], new[1] marker="^")
plt.xlabel('length')
plt.ylabel('weight')
plt.show

In [ ]:
# 정규화된 데이터로 학습
kn.fit(train_scaled, train_target)

In [ ]:
# Test도 정규화
test_scaled = (test_input - mean) / std

In [ ]:
kn.score(test_scaled, test_target)

In [ ]:
#수상한 도미도 정상적으로 도미로 분류
print(kn.predict([new]))

1. 특징(X) / 정답(Y) - ALL
특징(길이, 무게) / 정답(0 or 1)

2. Train/Test 데이터 분리
7:3, 8:2
클래스별로 분리

3. 정규화(특징 데이터)
표준점수(z-score)
/0~1
/min-max 정규화 함수(X) : 비추
